# 配置文件

DAILY_TIME: "2:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2020-05-20" # 纪念日
CITY: "北京"

BIRTHDAY:
  - "01-01"

APP_ID: "id"
APP_SECRET: "secret"

USER_ID: 
  - "id"
  - "id"
TEMPLATE_ID: "id"
