# 配置文件

DAILY_TIME: "9:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2021-12-03" # 纪念日
CITY: "洛阳"

BIRTHDAY:
  - "03-06"

APP_ID: "wx56ee245290dc2dc0"
APP_SECRET: "7175230290edea36606fddff2d6ef85f"

USER_ID: 
  - "oXKys58QTS2kWBG8hAs_nmCG5jqs"
  - "oXKys52G0hnh94UlhPG9DXXp31jI"
TEMPLATE_ID: "HdPaqo8yv1AC1I2bXb7wDyxJxLr3WQrhg0LPi-JoHKI	"
